---
services:

#### 1-Basic
  docker:
    image: "docker:20.10-dind"
    profiles:
      - "1-basic"
    privileged: true
    ports:
      # Expose docker API on host port 3376
      - "127.0.0.1:3376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - "ca_certs:/certs/ca"
      - "server_certs_basic:/certs/server"
      - "client_certs:/certs/client"
      - "/var/lib/docker"
volumes:
  ca_certs:
  client_certs:
  server_certs_basic:
